### ISSUE TITLE
Test failures on SIG 3D

### ISSUE THREAD

**Issue by massea** [IGNF/geoxygene#1]
When building geoxygene with Maven, test failures on Geoxygene SIG 3D

> Failed tests: 
  TestUtil.testCenterOf18:669 Volume under surface is incorrect expected:<309892.99593419785> but was:<309892.9974804691>
  TestUtil.testCenterOf21:756 Volume in triangulated solid is incorrect expected:<15962.072091309145> but was:<15962.071444940824>
  TestPlanEquation.testPlanEquation4:199 Randomly created plane equation is incorrect expected:<0.0> but was:<-4.572956008530582E-6>
  TestPlanEquation.testPlanEquation7:309 a coefficient in plane equation is incorrect expected:<NaN> but was:<0.0>
  TestPlanEquation.testPlanEquation10:429 Randomly created plane equation is incorrect expected:<0.0> but was:<-1.4627180000559292E-5>
  TestPlanEquation.testPlanEquation20:754 Triangle intersection with plane is incorrect
  TestPlanEquation.testPlanEquation23:853 Equation value on point is incorrect expected:<-22.27335446288359> but was:<-22.273354>
  TestUtil.testCenterOf18:669 Volume under surface is incorrect expected:<71617.23938811217> but was:<71617.23754183094>
  TestUtil.testCenterOf21:756 Volume in triangulated solid is incorrect expected:<81481.8379595562> but was:<81481.83541728824>
  TestUtil.testCenterOf22:781 Volume in triangulated solid is incorrect expected:<50006.46512055735> but was:<50006.465616>
  TestPlanEquation.testPlanEquation4:199 Randomly created plane equation is incorrect expected:<0.0> but was:<1.298957200290829E-5>
  TestPlanEquation.testPlanEquation7:309 a coefficient in plane equation is incorrect expected:<NaN> but was:<0.0>
  TestPlanEquation.testPlanEquation10:429 Randomly created plane equation is incorrect expected:<0.0> but was:<3.6776300760266167E-7>
  TestPlanEquation.testPlanEquation20:754 Triangle intersection with plane is incorrect
  TestPlanEquation.testPlanEquation23:853 Equation value on point is incorrect expected:<-93.33376586062427> but was:<-93.333766>

**Comment by mbrasebin** [comment]
The bug seems to be due to some modifications in DirectPosition class where coordinates are rounded to 6 decimals.

=> This modification for example :
  public void setX(final double x) {
    this.coordinate[0] = Math.round(x * Math.pow(10, precision))
        / Math.pow(10, precision);
  }

 So there are some numerical errors in volume assessment and other operations like that. We will discuss with the author of this code about how to manage the precision properly.

**Comment by mbrasebin** [comment]
On my computer the tests pass. Can you check it and mark as resolved if it is ok ?

**Comment by massea** [comment]
Still fails for me.

**Comment by massea** [comment]
#1 closed

**Comment by mbrasebin** [comment]
It is properly corrected now, option fn is removed.
