### ISSUE TITLE
1.9 release still references com.vividsolutions.jts

### ISSUE THREAD

**Issue by micycle1** [IGNF/geoxygene#25]
The files in the 1.9 release .zip on _Github releases_ still references `com.vividsolutions.jts` and not `org.locationtech.jts`. Based on one of the [PRs](https://github.com/IGNF/geoxygene/pull/21) before this date, I would have though this release references the newer version of JTS.

**Comment by julienperret** [comment]
Good point.
Commit 25929e4 fixes it.
Version 1.10-SNAPSHOT does not reference com.vividsolutions.jts anymore and further releases should not either.
Thank you
