### ISSUE TITLE
Loading feature  with no geometry from ShapeFileReader

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/geoxygene#3]
Dear contributors,

I d'like to add the possibility to load  features that have no geometry with the  shapefile reader.

This functionality may be useful because some standards allow this possibility.

The question is :  
- May it be a default behaviour ? Will it cause some issues for some apps ?
- If not, how can I implement it properly ? A method loadWithNullGeometryFeature ? A static parameter to define before loading ? A new parameter in the read method ?

Thanks for your feedback

Mickaël

**Comment by mborne** [comment]
Then, it's sometimes usefull to produce EMPTY geometries.

For example : 
- Input : A set of parcels
- Output : A set of building according to urbanism rules for each parcel

To output indicators if generation is not possible of some parcels, you need to produce features with EMPTY geometries.

**Comment by HueyNemud** [comment]
As Mickael (The Second)  pointed out,  features with empty geometries would
make sense in various situations: missing data,  empty output of a spatial
algorithm. Empty is an equivalent of "undefined/uninitialized".  We might
even consider all features attributes to be empty until something define
them.

On the other hand, null geometries should happen only when something went
wrong (invalid output,  user error,...)

Concerning the implementation, something possible is to define an
EmptyObject that inherits Object. The key advantages of this is that :
1-empty objects can define default behaviors
2-you can specify new default behaviors just by creating new types of
EmptyObjects.

**Comment by mborne** [comment]
Agree with Empty by default.

For implementation, it's important to inherit from Geometry. I would "mimic" JTS and GEOS using Empty GeometryCollection (I'm pretty sure it's what geoxygene does for "emty" intersections)
