### ISSUE TITLE
Duplicate ShapeFileReader in GeOxygene

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/geoxygene#5]
Hello,

as I am testing the upgrade of GeoTools version, I detected a code that seems to use GeoTools to load Shapefile in projet geoxygene-cartagen. It concerns the class fr.ign.cogit.cartagen.software.dataset.ShapeFileLoader.

 May it be interesting to make evolve it and to integrate the main ShapeFileReader from geoxygene-io ?

Mickaël

**Comment by gtouya** [comment]
Not sure this class is still used. But the loading of shapefiles in Cartagen is different as it does not create DefaultFeature instances from the shapefiles, but Building instances for building shapefiles, etc. So I don't think it's a duplicate code. I'll have a look when I come back.

Guillaume

**Comment by mbrasebin** [comment]
Okay, it just to keep a trace and to ease the future updates of geotools version.

**Comment by mbrasebin** [comment]
I do not create a new topic because it is related but the class GeOxygeneGeometryUserType is the same in geoxygene-cartagen/fr.ign.cogit.cartagen.core.persistence and geoxygene-database/r.ign.cogit.geoxygene.datatools.hibernate

**Comment by mborne** [comment]
@mbrasebin, I think you could create a new issue as it would be enougth to inherit fr.ign.cogit.cartagen.core.persistence.GeOxygeneGeometryUserType from fr.ign.cogit.geoxygene.datatools.hibernate.GeOxygeneGeometryUserType to remove code duplication.

**Comment by mbrasebin** [comment]
Done for GeOxygeneGeometryUserType in commit 34fdeed the class of cartagen inherits from fr.ign.cogit.geoxygene.datatools.hibernate.GeOxygeneGeometryUserType 

There is still a duplicate ShapeFileReader

**Comment by mbrasebin** [comment]
Problem solved :)
