### ISSUE TITLE
Update of GeOxygene dependencies (geotools, hibernate)

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/geoxygene#6]
Hello,

several dependencies of GeOxygene are really out-dated such as Geotools (version 8.4 was used vs version 15 actually released) or Hibernate (old version 3 vs current version 5). It causes some incompatibilities when we work with some other projects.

I created a branch in order to test the update of these libraries, it causes some minor changes (2a19b171ad16eea945f6ba03be747fc17f97e701).

The dependencies changed are :
- Update of geotools from v8 to v14.4, 
- Hibernate from v3 to v5, postgresql from v8.4 to v9.1, 
- Postgis from v1.5 to v2 and jfreechart to 1.0.13. 

In main pom.xml, new version controllers are added : hibernate.version, postgresql.version

So now the work is to :
- Check if all the projects are ok with this version (mainly test shapefile and hibernate)
- Decide a way to integrate this branch (the version of the branch is 1.9-SNAPSHOT to avoid conflict in case of deployment)

Thanks in advance for your participation.

**Comment by massea** [comment]
I test a build and it failed at geoxygene-io.

Running fr.ign.cogit.geoxygene.io.TestShapeFileWriter
 INFO [ENGINE] dataFileCache open start
TRACE [ENGINE] NIO buffer instance, file size 16777216
juil. 25, 2016 3:42:29 PM org.geotools.data.shapefile.files.MemoryMapCache cleanFileCache
AVERTISSEMENT: An error occurred while trying to clean the memory map cache
java.io.IOException: La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte

BTW, i made that test with W7/Eclipse Mars.2/JDK1.8.0_71

**Comment by mbrasebin** [comment]
Normally, it is corrected.

**Comment by ilokhat** [comment]
Merge is now done with master branch
